services:
  db:
    image: postgres:latest
    container_name: pg_database
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/
    networks:
      - cryptweb

  backend:
    build: .
    container_name: cryptweb_backend
    environment:
      - PORT=3000
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - cryptweb

  # trun_server:
  #   image: coturn/coturn
  #   container_name: trun_server
  #   ports:
  #     - "3478:3478"
  #     - "3478:3478/udp"
  #     - "5349:5349"
  #     - "5349:5349/udp"
  #     - "49152-65535:49152-65535/udp"

volumes:
  data:

networks:
  cryptweb:
